version: 0.2

env:
  variables:
    ECR_REPOSITORY: wordpress-ecr
    IMAGE_TAG: latest  # Pode ser substituído por $CODEBUILD_RESOLVED_SOURCE_VERSION para usar o SHA do commit

phases:
  pre_build:
    commands:
      - echo Iniciando a fase de pré-construção...
      - echo Autenticando no Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPOSITORY
      - echo REPOSITORY_URI=$REPOSITORY_URI
  build:
    commands:
      - echo Iniciando a fase de construção...
      - docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
      - docker tag $ECR_REPOSITORY:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Iniciando a fase de pós-construção...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Imagem Docker enviada para ECR: $REPOSITORY_URI:$IMAGE_TAG
      - echo "IMAGE_URI=$REPOSITORY_URI:$IMAGE_TAG" >> env.properties
artifacts:
  files:
    - env.properties
